train_file: ['./json_pretrain/coco_updated.json',
             # './json_pretrain/vg.json',
             ]
laion_path: ''   

pretrained: 'output/Pretrain/checkpoint_19.pth'
unlearned: 'output/unlearn/checkpoint_09.pth'

# size of vit model; base or large
vit: 'base'
vit_grad_ckpt: False
vit_ckpt_layer: 0

image_size: 224
batch_size: 16

queue_size: 57600
alpha: 0.4

# optimizer
weight_decay: 0.05
init_lr: 2e-5
min_lr: 1e-6
warmup_lr: 1e-6
lr_decay_rate: 0.9
max_epoch: 10
warmup_steps: 3000



